import { Button } from "@/components/ui/button";
import { trpc } from "@/lib/trpc";
import { Clock3, Loader2, ShieldCheck } from "lucide-react";
import { useEffect, useState } from "react";
import { toast } from "sonner";

const fields = [
  { key: "platform_availability_status", label: "Platform status", hint: "For example: ACTIVE, MAINTENANCE, or LIMITED" },
  { key: "platform_availability_start", label: "Availability start date", hint: "Use a clear date, such as 01 January 2026" },
  { key: "platform_availability_end", label: "Planned availability until", hint: "Use a clear date, such as 31 December 2026" },
  { key: "platform_reliability_message", label: "Reliability message", hint: "Member-facing availability information" },
  { key: "platform_maintenance_notice", label: "Maintenance notice", hint: "Leave blank when no notice applies" },
  { key: "platform_announcement", label: "Optional announcement", hint: "Member-facing operational announcement" },
  { key: "platform_timezone", label: "Platform timezone", hint: "Use an IANA timezone, such as Asia/Karachi" },
] as const;

export default function AdminAvailability() {
  const settings = trpc.admin.settings.useQuery(); const update = trpc.admin.updateSetting.useMutation(); const [values, setValues] = useState<Record<string, string>>({});
  useEffect(() => { if (!settings.data) return; setValues(Object.fromEntries(settings.data.map(setting => [setting.settingKey, setting.settingValue]))); }, [settings.data]);
  const save = async (key: string) => { try { await update.mutateAsync({ settingKey: key, settingValue: values[key] ?? "" }); await settings.refetch(); toast.success("Platform availability setting saved successfully and reloaded from the backend."); } catch (error) { toast.error(error instanceof Error ? error.message : "Availability information could not be saved."); } };
  return <div><div className="mb-7"><p className="text-xs font-extrabold uppercase tracking-[.18em] text-[#13897f]">Administrator workspace</p><h1 className="mt-2 text-2xl font-extrabold tracking-[-.035em] text-[#10233f] sm:text-3xl">Platform availability</h1><p className="mt-2 max-w-3xl text-sm leading-6 text-slate-600">Publish the availability window, operational status, maintenance information, and day-boundary timezone that members see in their workspace. Every change is stored with an audit record and reloaded after save.</p></div><div className="grid gap-5 xl:grid-cols-[.85fr_1.15fr]"><section className="rounded-2xl bg-[#10233f] p-6 text-white"><Clock3 className="text-[#7cebe1]" size={24} /><p className="mt-5 text-xs font-bold uppercase tracking-[.15em] text-[#7cebe1]">Current member-facing status</p><h2 className="mt-2 text-2xl font-extrabold">{values.platform_availability_status || "Not configured"}</h2><p className="mt-4 text-sm leading-6 text-slate-300">{values.platform_reliability_message || "Configure the availability message before public launch."}</p><div className="mt-6 space-y-3 text-sm"><div className="rounded-xl bg-white/10 p-3"><span className="text-slate-300">Available from</span><p className="mt-1 font-bold">{values.platform_availability_start || "Not set"}</p></div><div className="rounded-xl bg-white/10 p-3"><span className="text-slate-300">Planned until</span><p className="mt-1 font-bold">{values.platform_availability_end || "Not set"}</p></div><p className="flex gap-2 text-xs leading-5 text-slate-400"><ShieldCheck className="shrink-0 text-[#7cebe1]" size={15} />The configured timezone controls daily video reward eligibility. Use one consistent operational timezone.</p></div></section><section className="rounded-2xl border border-slate-200 bg-white p-6"><div className="space-y-5">{fields.map(field => <label key={field.key} className="grid gap-1.5 text-sm font-bold text-slate-700"><span>{field.label}<small className="ml-2 font-normal text-slate-400">{field.hint}</small></span>{field.key.includes("message") || field.key.includes("notice") || field.key.includes("announcement") ? <textarea value={values[field.key] ?? ""} onChange={event => setValues(current => ({ ...current, [field.key]: event.target.value }))} rows={3} className="rounded-xl border border-slate-200 p-3 text-sm font-medium outline-none focus:border-[#20bdb2]" /> : <input value={values[field.key] ?? ""} onChange={event => setValues(current => ({ ...current, [field.key]: event.target.value }))} className="h-11 rounded-xl border border-slate-200 px-3 text-sm font-medium outline-none focus:border-[#20bdb2]" />}<Button disabled={update.isPending} onClick={() => void save(field.key)} variant="outline" className="justify-self-start rounded-xl font-bold">{update.isPending ? <Loader2 className="animate-spin" size={16} /> : `Save ${field.label}`}</Button></label>)}</div></section></div></div>;
}
