import { useAuth } from "@/_core/hooks/useAuth";
import { Button } from "@/components/ui/button";
import { trpc } from "@/lib/trpc";
import { INITIAL_PACKAGES, formatPkr } from "@shared/platform";
import { AlertTriangle, ArrowRight, BadgeCheck, Bell, CheckCircle2, CircleDollarSign, Clock3, CreditCard, FileImage, Landmark, Loader2, Megaphone, Play, ShieldCheck, type LucideIcon, UserCircle2, WalletCards } from "lucide-react";
import { useEffect, useMemo, useState } from "react";
import { toast } from "sonner";
import { useLocation } from "wouter";

function PageIntro({ eyebrow, title, description, action }: { eyebrow: string; title: string; description: string; action?: React.ReactNode }) {
  return <div className="mb-7 flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><p className="text-xs font-extrabold uppercase tracking-[.18em] text-[#13897f]">{eyebrow}</p><h1 className="mt-2 text-2xl font-extrabold tracking-[-.035em] text-[#10233f] sm:text-3xl">{title}</h1><p className="mt-2 max-w-2xl text-sm leading-6 text-slate-600">{description}</p></div>{action}</div>;
}

const dateFormat = new Intl.DateTimeFormat("en-PK", { dateStyle: "medium", timeStyle: "short" });
const statusClass: Record<string, string> = { active: "bg-emerald-50 text-emerald-700", pending: "bg-amber-50 text-amber-700", approved: "bg-emerald-50 text-emerald-700", paid: "bg-emerald-50 text-emerald-700", processing: "bg-blue-50 text-blue-700", rejected: "bg-rose-50 text-rose-700", cancelled: "bg-slate-100 text-slate-600" };

export function MemberOverview() {
  const [, setLocation] = useLocation();
  const { user } = useAuth();
  const overview = trpc.dashboard.overview.useQuery();
  const campaigns = trpc.ads.available.useQuery();
  const settings = trpc.platform.settings.useQuery();
  const data = overview.data;
  const dailyLimit = data?.membership?.package.dailyAdLimit ?? 0;
  const availability = settings.data;
  const metrics = [
    ["Available balance", formatPkr(data?.wallet.availableBalancePaisa ?? 0), WalletCards, "Available for eligible withdrawal requests"],
    ["Total rewards", formatPkr(data?.wallet.lifetimeEarnedPaisa ?? 0), CircleDollarSign, "Validated advertising rewards recorded"],
    ["Today’s earnings", formatPkr(data?.todayEarningsPaisa ?? 0), BadgeCheck, "Only after completion validation"],
    ["Video rewards today", data?.todayVideoRewards ?? 0, Play, `Daily reset uses ${data?.platformTimeZone ?? "Asia/Karachi"}`],
  ];
  return <div>
    <PageIntro eyebrow="Member workspace" title={`Welcome${user?.name ? `, ${user.name.split(" ")[0]}` : ""}`} description="Your balance reflects validated activity only. Review current eligibility before starting a campaign, video session, or request." action={<div className="flex gap-2"><Button onClick={() => setLocation("/dashboard/videos")} variant="outline" className="rounded-xl font-bold"><Play className="mr-2" size={17} />Package videos</Button><Button onClick={() => setLocation("/dashboard/ads")} className="rounded-xl bg-[#10233f] font-bold hover:bg-[#19375f]"><Megaphone className="mr-2" size={17} />Available ads</Button></div>} />
    {overview.isLoading ? <div className="grid min-h-64 place-items-center"><Loader2 className="animate-spin text-[#168d86]" /></div> : <>
      <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{(metrics as unknown as Array<[string, string, LucideIcon, string]>).map(([label, value, Icon, description]) => <article key={label} className="rounded-2xl border border-slate-200 bg-white p-5 shadow-[0_8px_24px_rgba(16,35,63,.04)]"><div className="flex items-start justify-between"><p className="text-xs font-bold uppercase tracking-[.12em] text-slate-500">{label}</p><span className="grid h-9 w-9 place-items-center rounded-xl bg-[#ebfbf9] text-[#13897f]"><Icon size={18} /></span></div><p className="mt-5 text-2xl font-extrabold tracking-[-.035em] text-[#10233f]">{value}</p><p className="mt-2 text-xs leading-5 text-slate-500">{description}</p></article>)}</div>
      <div className="mt-5 grid gap-5 xl:grid-cols-[1.1fr_.9fr]">
        <section className="rounded-2xl bg-[#10233f] p-6 text-white"><div className="flex items-start justify-between gap-4"><div><p className="text-xs font-bold uppercase tracking-[.16em] text-[#7cebe1]">Membership access</p><h2 className="mt-2 text-2xl font-extrabold">{data?.membership?.package.name ?? "No active membership"}</h2></div><ShieldCheck className="text-[#6ee7dc]" size={24} /></div><p className="mt-4 max-w-lg text-sm leading-6 text-slate-300">{data?.membership ? `Active package eligibility is reviewed against its configured rules. ${data.membership.membership.expiresAt ? `Current access expires ${new Date(data.membership.membership.expiresAt).toLocaleDateString("en-PK")}.` : ""}` : "Submit a membership payment proof to begin the administrative verification workflow. Campaign rewards are not available until access is activated."}</p><div className="mt-6 flex flex-wrap gap-3"><span className="rounded-xl bg-white/10 px-3 py-2 text-sm font-bold">Ads today: {data?.todayViews ?? 0} / {dailyLimit || "—"}</span><span className="rounded-xl bg-white/10 px-3 py-2 text-sm font-bold">Video rewards: {data?.todayVideoRewards ?? 0}</span><Button onClick={() => setLocation("/dashboard/membership")} className="rounded-xl bg-[#22d3c5] font-bold text-[#06192f] hover:bg-[#8ff4ea]">Membership & payment <ArrowRight className="ml-2" size={16} /></Button></div></section>
        <section className="rounded-2xl border border-slate-200 bg-white p-6"><div className="flex items-center justify-between"><div><p className="text-xs font-bold uppercase tracking-[.14em] text-slate-500">Notifications</p><h2 className="mt-1 text-lg font-extrabold">Account updates</h2></div><Bell className="text-slate-400" size={20} /></div><div className="mt-5 space-y-4">{data?.recentNotifications?.length ? data.recentNotifications.map(note => <div key={note.id} className="flex gap-3"><span className={`mt-1 h-2 w-2 shrink-0 rounded-full ${note.type === "warning" || note.type === "security" ? "bg-amber-400" : "bg-[#21bfb4]"}`} /><div><p className="text-sm font-bold text-[#10233f]">{note.title}</p><p className="mt-1 text-xs leading-5 text-slate-500">{note.message}</p></div></div>) : <p className="rounded-xl bg-slate-50 p-4 text-sm leading-6 text-slate-500">Important account and verification updates will appear here.</p>}</div></section>
      </div>
      <div className="mt-5 grid gap-5 xl:grid-cols-[1.08fr_.92fr]">
        <section className="rounded-2xl border border-slate-200 bg-white p-6"><div className="flex items-center justify-between"><div><p className="text-xs font-bold uppercase tracking-[.14em] text-slate-500">Eligible campaigns</p><h2 className="mt-1 text-lg font-extrabold">Available for your package</h2></div><Megaphone className="text-[#168d86]" size={20} /></div>{campaigns.data?.campaigns?.length ? <div className="mt-5 space-y-3">{campaigns.data.campaigns.slice(0, 3).map(campaign => <div key={campaign.id} className="flex items-center justify-between gap-4 rounded-xl bg-slate-50 p-3"><div><p className="text-sm font-bold text-[#10233f]">{campaign.title}</p><p className="mt-1 text-xs text-slate-500">{campaign.advertiser} · {campaign.durationSeconds}s · {formatPkr(campaign.rewardPaisa)}</p><p className="mt-1 text-[11px] text-slate-500">{new Date(campaign.startAt).toLocaleDateString("en-PK")} – {new Date(campaign.endAt).toLocaleDateString("en-PK")} · {campaign.eligiblePackageId ? `${campaigns.data.membership?.package.name ?? "Your"} package` : "All active packages"}</p></div><Button onClick={() => setLocation("/dashboard/ads")} size="sm" variant="outline" className="rounded-lg">View</Button></div>)}</div> : <p className="mt-5 rounded-xl bg-slate-50 p-4 text-sm leading-6 text-slate-500">No active campaigns currently match your membership package, date window, and campaign controls.</p>}</section>
        <section className="rounded-2xl border border-slate-200 bg-white p-6"><div className="flex items-center justify-between"><div><p className="text-xs font-bold uppercase tracking-[.14em] text-slate-500">Platform availability</p><h2 className="mt-1 text-lg font-extrabold">{availability?.platform_availability_status || "Status not configured"}</h2></div><Clock3 className="text-[#168d86]" size={20} /></div><div className="mt-5 space-y-3 text-sm"><p className="leading-6 text-slate-600">{availability?.platform_reliability_message || "Platform availability information has not yet been configured."}</p>{availability?.platform_announcement && <p className="rounded-xl border border-[#bceee9] bg-[#f0fdfa] p-3 text-xs leading-5 text-[#176d68]">{availability.platform_announcement}</p>}<div className="grid grid-cols-2 gap-3 text-xs"><p className="rounded-lg bg-slate-50 p-3 text-slate-500">Available from<strong className="mt-1 block text-[#10233f]">{availability?.platform_availability_start || "Not set"}</strong></p><p className="rounded-lg bg-slate-50 p-3 text-slate-500">Planned until<strong className="mt-1 block text-[#10233f]">{availability?.platform_availability_end || "Not set"}</strong></p></div>{availability?.platform_maintenance_notice && <p className="text-xs leading-5 text-amber-700">Maintenance: {availability.platform_maintenance_notice}</p>}</div></section>
      </div>
      <section className="mt-5 overflow-hidden rounded-2xl border border-slate-200 bg-white"><div className="flex items-center justify-between border-b border-slate-100 px-6 py-5"><div><p className="text-xs font-bold uppercase tracking-[.14em] text-slate-500">Earnings ledger</p><h2 className="mt-1 text-lg font-extrabold">Recent activity</h2></div><span className="text-xs font-semibold text-slate-500">Every balance change is recorded</span></div>{data?.recentLedger?.length ? <div className="divide-y divide-slate-100">{data.recentLedger.map(entry => <div key={entry.id} className="flex items-center justify-between gap-4 px-6 py-4"><div><p className="text-sm font-bold text-[#10233f]">{entry.description}</p><p className="mt-1 text-xs text-slate-500">{dateFormat.format(new Date(entry.createdAt))}</p></div><p className={`text-sm font-extrabold ${entry.direction === "credit" ? "text-emerald-600" : "text-[#10233f]"}`}>{entry.direction === "credit" ? "+" : ""}{formatPkr(entry.amountPaisa)}</p></div>)}</div> : <div className="px-6 py-10 text-center text-sm text-slate-500">No ledger activity has been recorded for this account.</div>}</section>
    </>}
  </div>;
}

export function MemberAds() {
  const ads = trpc.ads.available.useQuery();
  const start = trpc.ads.start.useMutation();
  const complete = trpc.ads.complete.useMutation();
  const [session, setSession] = useState<{ token: string; remaining: number } | null>(null);
  useEffect(() => {
    if (!session || session.remaining <= 0) return;
    const interval = window.setInterval(() => setSession(current => current ? { ...current, remaining: Math.max(0, current.remaining - 1) } : current), 1_000);
    return () => window.clearInterval(interval);
  }, [session]);
  const begin = async (campaignId: number) => {
    try { const result = await start.mutateAsync({ campaignId }); setSession({ token: result.sessionToken, remaining: result.requiredSeconds }); toast.success("Ad session started. Keep this page open until the timer finishes."); } catch (error) { toast.error(error instanceof Error ? error.message : "Could not start this campaign."); }
  };
  const finalize = async () => {
    if (!session) return;
    try { const result = await complete.mutateAsync({ sessionToken: session.token }); toast.success(`Validated reward of ${formatPkr(result.rewardPaisa)} recorded.`); setSession(null); ads.refetch(); } catch (error) { toast.error(error instanceof Error ? error.message : "The session could not be completed."); setSession(null); }
  };
  return <div><PageIntro eyebrow="Eligible activity" title="Available advertisements" description="Rewards are not granted for clicks. Begin a session, remain for the required duration, and let the server validate eligibility before any credit is recorded." />
    {session ? <section className="mb-6 rounded-2xl bg-[#10233f] p-6 text-white"><div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-center"><div><p className="text-xs font-bold uppercase tracking-[.16em] text-[#7cebe1]">Active ad session</p><h2 className="mt-2 text-xl font-extrabold">Completion timer in progress</h2><p className="mt-2 text-sm text-slate-300">Do not refresh or open another session. The server uses the original start time for validation.</p></div><div className="flex items-center gap-4"><p className="text-4xl font-extrabold tabular-nums text-[#6ee7dc]">{session.remaining}s</p><Button disabled={session.remaining > 0 || complete.isPending} onClick={finalize} className="rounded-xl bg-[#22d3c5] font-bold text-[#06192f] disabled:opacity-40">{complete.isPending ? <Loader2 className="animate-spin" size={16} /> : "Complete session"}</Button></div></div></section> : null}
    {!ads.data?.membership ? <section className="rounded-2xl border border-dashed border-slate-300 bg-white p-10 text-center"><ShieldCheck className="mx-auto text-[#22aaa1]" size={30} /><h2 className="mt-4 text-xl font-extrabold">An active membership is required</h2><p className="mx-auto mt-2 max-w-lg text-sm leading-6 text-slate-600">Once an administrator verifies your membership payment, eligible active campaigns can appear here. Availability is never guaranteed.</p></section> : <><div className="mb-5 flex items-center justify-between rounded-xl border border-[#beece6] bg-[#f0fdfa] px-4 py-3 text-sm text-[#176d68]"><span className="flex items-center gap-2"><CheckCircle2 size={16} /> Your configured daily limit is {ads.data.membership.package.dailyAdLimit} advertisements.</span><span className="font-bold">Completed today: {ads.data.completedToday}</span></div><div className="grid gap-5 lg:grid-cols-2">{ads.data.campaigns.map(campaign => <article key={campaign.id} className="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-[0_8px_24px_rgba(16,35,63,.04)]"><div className="h-2 bg-gradient-to-r from-[#21c8b9] via-[#73dfd4] to-[#e0f7f5]" /><div className="p-6"><div className="flex items-start justify-between gap-4"><div><p className="text-xs font-bold uppercase tracking-[.14em] text-[#168d86]">{campaign.advertiser}</p><h2 className="mt-2 text-xl font-extrabold text-[#10233f]">{campaign.title}</h2></div><span className="rounded-xl bg-[#ebfbf9] px-3 py-2 text-sm font-extrabold text-[#10877f]">{formatPkr(campaign.rewardPaisa)}</span></div><p className="mt-4 min-h-12 text-sm leading-6 text-slate-600">{campaign.description || "This campaign has not provided an additional description."}</p><div className="mt-5 flex items-center justify-between border-y border-slate-100 py-4 text-sm"><span className="flex items-center gap-2 text-slate-500"><Clock3 size={16} />{campaign.durationSeconds} seconds</span><span className="font-semibold text-slate-600">Server-validated reward</span></div><Button disabled={!!session || start.isPending} onClick={() => begin(campaign.id)} className="mt-5 w-full rounded-xl bg-[#10233f] font-bold hover:bg-[#19375f]"><Play className="mr-2" size={16} />Watch advertisement</Button></div></article>)}</div>{!ads.data.campaigns.length && <section className="mt-5 rounded-2xl border border-dashed border-slate-300 bg-white p-10 text-center"><Megaphone className="mx-auto text-slate-400" size={28} /><h2 className="mt-4 text-lg font-extrabold">No eligible campaigns right now</h2><p className="mt-2 text-sm text-slate-500">Campaign availability depends on active advertiser budgets, dates, and platform controls.</p></section>}</>}
  </div>;
}

async function fileToBase64(file: File) {
  return new Promise<string>((resolve, reject) => { const reader = new FileReader(); reader.onload = () => resolve(String(reader.result).split(",")[1] ?? ""); reader.onerror = () => reject(new Error("The image could not be read.")); reader.readAsDataURL(file); });
}

export function MemberMembership() {
  const configured = trpc.platform.packages.useQuery();
  const instructions = trpc.payments.instructions.useQuery();
  const payments = trpc.payments.list.useQuery();
  const submit = trpc.payments.submit.useMutation();
  const [selectedId, setSelectedId] = useState<number | null>(null);
  const [method, setMethod] = useState<"jazzcash" | "easypaisa" | "bank_transfer">("jazzcash");
  const [senderAccount, setSenderAccount] = useState("");
  const [transactionId, setTransactionId] = useState("");
  const [note, setNote] = useState("");
  const [file, setFile] = useState<File | null>(null);
  const packages = configured.data ?? [];
  const selected = packages.find(item => item.id === selectedId);
  const displayPackages = packages.length ? packages : INITIAL_PACKAGES;
  useEffect(() => {
    const packageParam = Number(new URLSearchParams(typeof window === "undefined" ? "" : window.location.search).get("package"));
    if (packageParam && packages.some(item => item.id === packageParam)) setSelectedId(packageParam);
  }, [packages]);
  const onSubmit = async (event: React.FormEvent) => { event.preventDefault(); if (!selected) return toast.error("Choose a membership from the configured list."); try { const screenshot = file ? { fileName: file.name, mimeType: file.type, base64: await fileToBase64(file) } : undefined; await submit.mutateAsync({ packageId: selected.id, paymentMethod: method, amountPaisa: selected.pricePaisa, senderAccount, transactionId, additionalNote: note || undefined, screenshot }); toast.success("Payment proof submitted for administrative review."); setSenderAccount(""); setTransactionId(""); setNote(""); setFile(null); payments.refetch(); } catch (error) { toast.error(error instanceof Error ? error.message : "Payment proof could not be submitted."); } };
  return <div><PageIntro eyebrow="Membership & verification" title="Select access, then submit payment proof" description="Review the package terms and company payment details before submitting. Membership activation occurs only after a successful administrative verification." />
    <div className="grid gap-5 lg:grid-cols-[1.02fr_.98fr]"><section className="grid gap-4">{displayPackages.map((tier, index) => { const selectable = "id" in tier; const isSelected = selectable && selectedId === tier.id; return <button key={tier.name} disabled={!selectable} onClick={() => selectable && setSelectedId(tier.id)} className={`rounded-2xl border p-5 text-left transition ${isSelected ? "border-[#20bdb2] bg-[#effcfb] ring-2 ring-[#9ae9e2]" : "border-slate-200 bg-white hover:border-slate-300"} disabled:cursor-not-allowed`}><div className="flex items-start justify-between gap-4"><div><p className="text-xs font-extrabold uppercase tracking-[.14em] text-[#168d86]">{tier.name}</p><p className="mt-2 text-2xl font-extrabold text-[#10233f]">{formatPkr(tier.pricePaisa)}</p><p className="mt-1 text-sm text-slate-500">Membership fee</p></div>{isSelected ? <CheckCircle2 className="text-[#17a097]" /> : <span className={`rounded-lg px-2.5 py-1 text-xs font-bold ${index === 1 ? "bg-[#fff3bf] text-[#816b19]" : "bg-slate-100 text-slate-600"}`}>{selectable ? "Select" : "Loading"}</span>}</div><div className="mt-4 flex gap-5 text-sm text-slate-600"><span>Eligible ad reward: <strong>{formatPkr(tier.rewardPerEligibleAdPaisa)}</strong></span><span>Initial limit: <strong>{tier.dailyAdLimit}/day</strong></span></div></button>})}</section>
      <section className="rounded-2xl border border-slate-200 bg-white p-6"><div className="flex items-center gap-3"><span className="grid h-10 w-10 place-items-center rounded-xl bg-[#ebfbf9] text-[#13897f]"><Landmark size={19} /></span><div><p className="text-xs font-bold uppercase tracking-[.14em] text-slate-500">Company payment information</p><h2 className="text-lg font-extrabold">Use only configured details</h2></div></div><div className="mt-5 rounded-xl bg-[#f8fafc] p-4 text-sm"><p className="font-bold text-[#10233f]">{instructions.data?.companyName ?? "[YOUR COMPANY NAME]"}</p><div className="mt-3 grid gap-2 text-slate-600"><p>JazzCash: <span className="font-semibold text-[#10233f]">{instructions.data?.jazzcashNumber ?? "[YOUR JAZZCASH NUMBER]"}</span></p><p>Easypaisa: <span className="font-semibold text-[#10233f]">{instructions.data?.easypaisaNumber ?? "[YOUR EASYPAISA NUMBER]"}</span></p><p>Account title: <span className="font-semibold text-[#10233f]">{instructions.data?.accountTitle ?? "[YOUR ACCOUNT TITLE]"}</span></p></div></div><div className="mt-4 flex gap-2 rounded-xl border border-amber-200 bg-amber-50 p-3 text-xs leading-5 text-amber-800"><AlertTriangle size={16} className="mt-0.5 shrink-0" /> Payment screenshots do not activate access automatically. Your submission remains pending until an administrator verifies it.</div>
        <form onSubmit={onSubmit} className="mt-5 space-y-4"><div className="grid gap-3 sm:grid-cols-2"><label className="grid gap-1.5 text-sm font-bold text-slate-700">Payment method<select value={method} onChange={event => setMethod(event.target.value as typeof method)} className="h-11 rounded-xl border border-slate-200 bg-white px-3 text-sm font-medium outline-none focus:border-[#20bdb2]"><option value="jazzcash">JazzCash</option><option value="easypaisa">Easypaisa</option><option value="bank_transfer">Bank transfer</option></select></label><label className="grid gap-1.5 text-sm font-bold text-slate-700">Sender account<input required value={senderAccount} onChange={event => setSenderAccount(event.target.value)} placeholder="Account or phone number" className="h-11 rounded-xl border border-slate-200 px-3 text-sm font-medium outline-none focus:border-[#20bdb2]" /></label></div><label className="grid gap-1.5 text-sm font-bold text-slate-700">Transaction ID<input required value={transactionId} onChange={event => setTransactionId(event.target.value)} placeholder="Payment reference" className="h-11 rounded-xl border border-slate-200 px-3 text-sm font-medium outline-none focus:border-[#20bdb2]" /></label><label className="grid gap-1.5 text-sm font-bold text-slate-700">Payment screenshot <span className="font-normal text-slate-500">Optional; JPG, PNG, or WebP up to 5 MB</span><input type="file" accept="image/jpeg,image/png,image/webp" onChange={event => setFile(event.target.files?.[0] ?? null)} className="block w-full rounded-xl border border-dashed border-slate-300 bg-slate-50 p-3 text-xs text-slate-600 file:mr-3 file:rounded-lg file:border-0 file:bg-[#e5faf8] file:px-3 file:py-1.5 file:text-xs file:font-bold file:text-[#0f827a]" /></label><label className="grid gap-1.5 text-sm font-bold text-slate-700">Additional note <textarea value={note} onChange={event => setNote(event.target.value)} rows={2} className="rounded-xl border border-slate-200 p-3 text-sm font-medium outline-none focus:border-[#20bdb2]" /></label><Button disabled={submit.isPending || !selected} className="w-full rounded-xl bg-[#10233f] font-bold hover:bg-[#19375f]">{submit.isPending ? <Loader2 className="animate-spin" size={17} /> : <><CreditCard className="mr-2" size={17} />Submit payment verification</>}</Button></form></section></div>
    <section className="mt-5 overflow-hidden rounded-2xl border border-slate-200 bg-white"><div className="border-b border-slate-100 px-6 py-5"><p className="text-xs font-bold uppercase tracking-[.14em] text-slate-500">Your submissions</p><h2 className="mt-1 text-lg font-extrabold">Payment verification history</h2></div>{payments.data?.length ? <div className="divide-y divide-slate-100">{payments.data.map(({ payment, package: packageInfo }) => <div key={payment.id} className="flex items-center justify-between gap-3 px-6 py-4"><div><p className="text-sm font-bold">{packageInfo.name} membership</p><p className="mt-1 text-xs text-slate-500">{dateFormat.format(new Date(payment.createdAt))} · {payment.transactionId}</p></div><div className="text-right"><p className="text-sm font-extrabold">{formatPkr(payment.amountPaisa)}</p><span className={`mt-1 inline-flex rounded-full px-2.5 py-1 text-[11px] font-bold capitalize ${statusClass[payment.status]}`}>{payment.status}</span></div></div>)}</div> : <div className="p-10 text-center text-sm text-slate-500">No payment proofs have been submitted.</div>}</section>
  </div>;
}

export function MemberWithdrawals() {
  const overview = trpc.dashboard.overview.useQuery();
  const settings = trpc.platform.settings.useQuery();
  const history = trpc.withdrawals.list.useQuery();
  const create = trpc.withdrawals.create.useMutation();
  const [amount, setAmount] = useState(""); const [method, setMethod] = useState<"jazzcash" | "easypaisa">("jazzcash"); const [holder, setHolder] = useState(""); const [account, setAccount] = useState("");
  const quote = useMemo(() => { const amountPaisa = Math.round(Number(amount || 0) * 100); const feePaisa = Number(settings.data?.withdrawal_fee_paisa ?? 15_000); return { amountPaisa, feePaisa, netPaisa: Math.max(0, amountPaisa - feePaisa) }; }, [amount, settings.data?.withdrawal_fee_paisa]);
  const submit = async (event: React.FormEvent) => { event.preventDefault(); try { await create.mutateAsync({ amountPaisa: quote.amountPaisa, paymentMethod: method, accountHolderName: holder, accountNumber: account }); toast.success("Withdrawal request submitted for review."); setAmount(""); setHolder(""); setAccount(""); overview.refetch(); history.refetch(); } catch (error) { toast.error(error instanceof Error ? error.message : "The withdrawal request could not be submitted."); } };
  return <div><PageIntro eyebrow="Balance request" title="Withdrawal request" description="Eligible balance is placed on hold when you submit a request. A payment is not automatic; an administrator reviews the destination and records the outcome." />
    <div className="grid gap-5 lg:grid-cols-[.88fr_1.12fr]"><section className="rounded-2xl bg-[#10233f] p-6 text-white"><p className="text-xs font-bold uppercase tracking-[.15em] text-[#7cebe1]">Withdrawal eligibility</p><p className="mt-5 text-4xl font-extrabold tracking-[-.04em]">{formatPkr(overview.data?.wallet.availableBalancePaisa ?? 0)}</p><p className="mt-2 text-sm text-slate-300">Available balance</p><div className="mt-7 grid gap-3"><div className="flex items-center justify-between rounded-xl bg-white/10 px-4 py-3 text-sm"><span className="text-slate-300">Minimum withdrawal</span><strong>{formatPkr(Number(settings.data?.minimum_withdrawal_paisa ?? 200_000))}</strong></div><div className="flex items-center justify-between rounded-xl bg-white/10 px-4 py-3 text-sm"><span className="text-slate-300">Withdrawal fee</span><strong>{formatPkr(Number(settings.data?.withdrawal_fee_paisa ?? 15_000))}</strong></div><p className="flex gap-2 pt-1 text-xs leading-5 text-slate-400"><ShieldCheck size={15} className="shrink-0 text-[#6ee7dc]" /> Payment account numbers are masked in history views. Suspicious requests may be held for review.</p></div></section>
      <form onSubmit={submit} className="rounded-2xl border border-slate-200 bg-white p-6"><h2 className="text-lg font-extrabold">Submit a documented request</h2><div className="mt-5 grid gap-4 sm:grid-cols-2"><label className="grid gap-1.5 text-sm font-bold text-slate-700">Amount (PKR)<input required inputMode="decimal" min="0" value={amount} onChange={event => setAmount(event.target.value)} placeholder="0" className="h-11 rounded-xl border border-slate-200 px-3 text-sm outline-none focus:border-[#20bdb2]" /></label><label className="grid gap-1.5 text-sm font-bold text-slate-700">Payment method<select value={method} onChange={event => setMethod(event.target.value as typeof method)} className="h-11 rounded-xl border border-slate-200 bg-white px-3 text-sm outline-none focus:border-[#20bdb2]"><option value="jazzcash">JazzCash</option><option value="easypaisa">Easypaisa</option></select></label><label className="grid gap-1.5 text-sm font-bold text-slate-700">Account holder name<input required value={holder} onChange={event => setHolder(event.target.value)} className="h-11 rounded-xl border border-slate-200 px-3 text-sm outline-none focus:border-[#20bdb2]" /></label><label className="grid gap-1.5 text-sm font-bold text-slate-700">{method === "jazzcash" ? "JazzCash" : "Easypaisa"} number<input required value={account} onChange={event => setAccount(event.target.value)} placeholder="03XXXXXXXXX" className="h-11 rounded-xl border border-slate-200 px-3 text-sm outline-none focus:border-[#20bdb2]" /></label></div><div className="mt-5 rounded-xl bg-[#f8fafc] p-4"><div className="flex justify-between text-sm"><span className="text-slate-500">Requested amount</span><strong>{formatPkr(quote.amountPaisa)}</strong></div><div className="mt-2 flex justify-between text-sm"><span className="text-slate-500">Withdrawal fee</span><strong>− {formatPkr(quote.feePaisa)}</strong></div><div className="mt-3 flex justify-between border-t border-slate-200 pt-3 text-sm"><span className="font-bold text-[#10233f]">Net amount</span><strong className="text-[#13897f]">{formatPkr(quote.netPaisa)}</strong></div></div><Button disabled={create.isPending} className="mt-5 w-full rounded-xl bg-[#10233f] font-bold hover:bg-[#19375f]">{create.isPending ? <Loader2 className="animate-spin" size={17} /> : "Submit withdrawal request"}</Button></form></div>
    <section className="mt-5 overflow-hidden rounded-2xl border border-slate-200 bg-white"><div className="border-b border-slate-100 px-6 py-5"><p className="text-xs font-bold uppercase tracking-[.14em] text-slate-500">Request history</p><h2 className="mt-1 text-lg font-extrabold">Withdrawal records</h2></div>{history.data?.length ? <div className="overflow-x-auto"><table className="w-full min-w-[680px] text-left text-sm"><thead className="bg-slate-50 text-xs uppercase tracking-[.1em] text-slate-500"><tr><th className="px-6 py-3 font-bold">Request</th><th className="px-4 py-3 font-bold">Destination</th><th className="px-4 py-3 font-bold">Net amount</th><th className="px-4 py-3 font-bold">Status</th></tr></thead><tbody className="divide-y divide-slate-100">{history.data.map(withdrawal => <tr key={withdrawal.id}><td className="px-6 py-4"><p className="font-bold text-[#10233f]">{formatPkr(withdrawal.amountPaisa)}</p><p className="mt-1 text-xs text-slate-500">{dateFormat.format(new Date(withdrawal.createdAt))}</p></td><td className="px-4 py-4 text-slate-600">{withdrawal.paymentMethod} · ••••{withdrawal.accountNumber.slice(-4)}</td><td className="px-4 py-4 font-bold">{formatPkr(withdrawal.netAmountPaisa)}</td><td className="px-4 py-4"><span className={`inline-flex rounded-full px-2.5 py-1 text-[11px] font-bold capitalize ${statusClass[withdrawal.status]}`}>{withdrawal.status}</span></td></tr>)}</tbody></table></div> : <div className="p-10 text-center text-sm text-slate-500">No withdrawal requests have been submitted.</div>}</section>
  </div>;
}

export function MemberProfile() {
  const profile = trpc.profile.get.useQuery();
  const update = trpc.profile.update.useMutation();
  const [name, setName] = useState("");
  const [phone, setPhone] = useState("");
  useEffect(() => {
    if (!profile.data) return;
    setName(profile.data.user.name ?? "");
    setPhone(profile.data.user.phone ?? "");
  }, [profile.data]);
  const submit = async (event: React.FormEvent) => {
    event.preventDefault();
    try {
      await update.mutateAsync({ name, phone: phone || undefined });
      toast.success("Profile updated with an audit record.");
      profile.refetch();
    } catch (error) {
      toast.error(error instanceof Error ? error.message : "Profile could not be updated.");
    }
  };
  return <div><PageIntro eyebrow="Account profile" title="Your account information" description="Keep permitted contact information current. Passwords and sign-in credentials are managed by the secure sign-in service and are never shown here." />
    <div className="grid gap-5 lg:grid-cols-[.8fr_1.2fr]"><section className="rounded-2xl bg-[#10233f] p-6 text-white"><span className="grid h-12 w-12 place-items-center rounded-2xl bg-white/10 text-[#6ee7dc]"><UserCircle2 size={25} /></span><h2 className="mt-5 text-xl font-extrabold">{profile.data?.user.name ?? "Member account"}</h2><p className="mt-2 text-sm text-slate-300">{profile.data?.user.email ?? "Email is managed by your sign-in provider."}</p><div className="mt-7 space-y-3 text-sm"><div className="rounded-xl bg-white/10 p-3"><span className="text-slate-300">Account status</span><p className="mt-1 font-bold capitalize">{profile.data?.user.accountStatus ?? "Loading"}</p></div><div className="rounded-xl bg-white/10 p-3"><span className="text-slate-300">Current membership</span><p className="mt-1 font-bold">{profile.data?.membership?.package.name ?? "No active membership"}</p></div><p className="px-1 text-xs leading-5 text-slate-400">Registration date: {profile.data?.user.createdAt ? new Date(profile.data.user.createdAt).toLocaleDateString("en-PK") : "—"}</p></div></section>
      <form onSubmit={submit} className="rounded-2xl border border-slate-200 bg-white p-6"><h2 className="text-lg font-extrabold">Permitted details</h2><p className="mt-2 text-sm leading-6 text-slate-600">Payment details are not stored in this profile and are requested only when you create a withdrawal request.</p><div className="mt-5 grid gap-4"><label className="grid gap-1.5 text-sm font-bold text-slate-700">Full name<input required value={name} onChange={event => setName(event.target.value)} className="h-11 rounded-xl border border-slate-200 px-3 text-sm outline-none focus:border-[#20bdb2]" /></label><label className="grid gap-1.5 text-sm font-bold text-slate-700">Pakistani mobile number <span className="font-normal text-slate-500">Optional; e.g. 03XXXXXXXXX</span><input value={phone} onChange={event => setPhone(event.target.value)} className="h-11 rounded-xl border border-slate-200 px-3 text-sm outline-none focus:border-[#20bdb2]" /></label><label className="grid gap-1.5 text-sm font-bold text-slate-700">Email <input disabled value={profile.data?.user.email ?? "Managed by sign-in provider"} className="h-11 rounded-xl border border-slate-200 bg-slate-50 px-3 text-sm text-slate-500" /></label></div><Button disabled={update.isPending} className="mt-6 rounded-xl bg-[#10233f] font-bold hover:bg-[#19375f]">{update.isPending ? <Loader2 className="animate-spin" size={17} /> : "Save permitted updates"}</Button></form></div>
    <PasswordSection hasPassword={profile.data?.hasPassword ?? false} onChanged={() => profile.refetch()} />
  </div>;
}

function PasswordSection({ hasPassword, onChanged }: { hasPassword: boolean; onChanged: () => void }) {
  const changePassword = trpc.profile.changePassword.useMutation();
  const [currentPassword, setCurrentPassword] = useState("");
  const [newPassword, setNewPassword] = useState("");
  const [confirmPassword, setConfirmPassword] = useState("");
  const submit = async (event: React.FormEvent) => {
    event.preventDefault();
    if (newPassword !== confirmPassword) {
      toast.error("The new passwords do not match.");
      return;
    }
    try {
      await changePassword.mutateAsync({ currentPassword: currentPassword || undefined, newPassword });
      setCurrentPassword("");
      setNewPassword("");
      setConfirmPassword("");
      toast.success(hasPassword ? "Password changed." : "Password set. You can now sign in with email and password too.");
      onChanged();
    } catch (error) {
      toast.error(error instanceof Error ? error.message : "The password could not be updated.");
    }
  };
  return <section className="mt-5 rounded-2xl border border-slate-200 bg-white p-6">
    <h2 className="text-lg font-extrabold">Sign-in password</h2>
    <p className="mt-2 text-sm leading-6 text-slate-600">{hasPassword ? "Change the password you use to sign in with your email." : "You signed up with Google. Set a password to also sign in with your email and password."}</p>
    <form onSubmit={submit} className="mt-5 grid gap-4 sm:max-w-md">
      {hasPassword && <label className="grid gap-1.5 text-sm font-bold text-slate-700">Current password<input required type="password" autoComplete="current-password" value={currentPassword} onChange={event => setCurrentPassword(event.target.value)} className="h-11 rounded-xl border border-slate-200 px-3 text-sm outline-none focus:border-[#20bdb2]" /></label>}
      <label className="grid gap-1.5 text-sm font-bold text-slate-700">{hasPassword ? "New password" : "Password"}<input required type="password" autoComplete="new-password" minLength={8} value={newPassword} onChange={event => setNewPassword(event.target.value)} className="h-11 rounded-xl border border-slate-200 px-3 text-sm outline-none focus:border-[#20bdb2]" placeholder="At least 8 characters" /></label>
      <label className="grid gap-1.5 text-sm font-bold text-slate-700">Confirm new password<input required type="password" autoComplete="new-password" minLength={8} value={confirmPassword} onChange={event => setConfirmPassword(event.target.value)} className="h-11 rounded-xl border border-slate-200 px-3 text-sm outline-none focus:border-[#20bdb2]" /></label>
      <div><Button disabled={changePassword.isPending} className="rounded-xl bg-[#10233f] font-bold hover:bg-[#19375f]">{changePassword.isPending ? <Loader2 className="animate-spin" size={17} /> : hasPassword ? "Change password" : "Set password"}</Button></div>
    </form>
  </section>;
}
