import { Button } from "@/components/ui/button";
import { trpc } from "@/lib/trpc";
import { formatPkr } from "@shared/platform";
import { Bell, CheckCheck, CircleDollarSign, Loader2, ReceiptText } from "lucide-react";
import { useState } from "react";
import { toast } from "sonner";

const dateFormat = new Intl.DateTimeFormat("en-PK", { dateStyle: "medium", timeStyle: "short" });

function Intro({ eyebrow, title, description }: { eyebrow: string; title: string; description: string }) {
  return <div className="mb-7"><p className="text-xs font-extrabold uppercase tracking-[.18em] text-[#13897f]">{eyebrow}</p><h1 className="mt-2 text-2xl font-extrabold tracking-[-.035em] text-[#10233f] sm:text-3xl">{title}</h1><p className="mt-2 max-w-2xl text-sm leading-6 text-slate-600">{description}</p></div>;
}

export function MemberEarnings() {
  const [period, setPeriod] = useState<"today" | "week" | "month" | "all">("all");
  const ledger = trpc.ledger.list.useQuery({ period });
  const labels = { today: "Today", week: "This week", month: "This month", all: "All time" };
  return <div><Intro eyebrow="Auditable earnings" title="Earnings and balance history" description="This ledger records validated rewards and other balance events. Entries reflect server-side rules, not browser-submitted reward amounts." /><div className="mb-5 flex flex-wrap gap-2">{(Object.keys(labels) as Array<keyof typeof labels>).map(key => <button key={key} onClick={() => setPeriod(key)} className={`rounded-xl px-4 py-2 text-sm font-bold transition ${period === key ? "bg-[#10233f] text-white" : "border border-slate-200 bg-white text-slate-600 hover:border-slate-300"}`}>{labels[key]}</button>)}</div><section className="overflow-hidden rounded-2xl border border-slate-200 bg-white"><div className="flex items-center justify-between border-b border-slate-100 px-6 py-5"><div><p className="text-xs font-bold uppercase tracking-[.14em] text-slate-500">Ledger entries</p><h2 className="mt-1 text-lg font-extrabold">{labels[period]}</h2></div><ReceiptText className="text-slate-400" size={20} /></div>{ledger.isLoading ? <div className="grid min-h-56 place-items-center"><Loader2 className="animate-spin text-[#13897f]" /></div> : ledger.data?.length ? <div className="divide-y divide-slate-100">{ledger.data.map(entry => <div key={entry.id} className="flex items-center justify-between gap-5 px-6 py-4"><div><p className="text-sm font-bold text-[#10233f]">{entry.description}</p><p className="mt-1 text-xs text-slate-500">{entry.transactionType.replaceAll("_", " ")} · {dateFormat.format(new Date(entry.createdAt))}</p></div><p className={`text-sm font-extrabold ${entry.direction === "credit" ? "text-emerald-600" : "text-[#10233f]"}`}>{entry.direction === "credit" ? "+" : ""}{formatPkr(entry.amountPaisa)}</p></div>)}</div> : <div className="p-12 text-center"><CircleDollarSign className="mx-auto text-slate-300" size={28} /><p className="mt-3 text-sm font-bold">No entries for this period</p><p className="mt-1 text-xs text-slate-500">Validated advertising rewards and request-related balance activity appear here.</p></div>}</section></div>;
}

export function MemberNotifications() {
  const notifications = trpc.notifications.list.useQuery();
  const markRead = trpc.notifications.markRead.useMutation();
  const markAll = async () => { try { await markRead.mutateAsync(); toast.success("Notifications marked as read."); notifications.refetch(); } catch (error) { toast.error(error instanceof Error ? error.message : "Notifications could not be updated."); } };
  return <div><Intro eyebrow="Account updates" title="Notifications" description="Security, payment, membership, reward, and withdrawal updates are delivered here with a retained timestamp." /><section className="overflow-hidden rounded-2xl border border-slate-200 bg-white"><div className="flex items-center justify-between border-b border-slate-100 px-6 py-5"><div><p className="text-xs font-bold uppercase tracking-[.14em] text-slate-500">Notification center</p><h2 className="mt-1 text-lg font-extrabold">Latest account messages</h2></div><Button disabled={markRead.isPending || !notifications.data?.some(item => !item.readAt)} onClick={markAll} variant="outline" className="rounded-xl border-slate-300 font-bold"><CheckCheck className="mr-2" size={16} />Mark all read</Button></div>{notifications.isLoading ? <div className="grid min-h-56 place-items-center"><Loader2 className="animate-spin text-[#13897f]" /></div> : notifications.data?.length ? <div className="divide-y divide-slate-100">{notifications.data.map(note => <div key={note.id} className={`flex gap-4 px-6 py-5 ${note.readAt ? "bg-white" : "bg-[#f3fdfa]"}`}><span className={`mt-1.5 h-2.5 w-2.5 shrink-0 rounded-full ${note.type === "warning" || note.type === "security" ? "bg-amber-400" : "bg-[#1ab7ac]"}`} /><div><div className="flex flex-wrap items-center gap-2"><p className="text-sm font-extrabold text-[#10233f]">{note.title}</p>{!note.readAt && <span className="rounded-full bg-[#dff8f5] px-2 py-0.5 text-[10px] font-bold text-[#13897f]">New</span>}</div><p className="mt-2 text-sm leading-6 text-slate-600">{note.message}</p><p className="mt-2 text-xs text-slate-500">{dateFormat.format(new Date(note.createdAt))}</p></div></div>)}</div> : <div className="p-12 text-center"><Bell className="mx-auto text-slate-300" size={28} /><p className="mt-3 text-sm font-bold">No notifications yet</p><p className="mt-1 text-xs text-slate-500">Future account updates will appear here.</p></div>}</section></div>;
}
