import { startLogin } from "@/const";
import { Button } from "@/components/ui/button";
import { LogIn, ShieldCheck } from "lucide-react";
import { useLocation } from "wouter";

export default function MemberAccess() {
  const [, setLocation] = useLocation();
  const selectedPackage = new URLSearchParams(typeof window === "undefined" ? "" : window.location.search).get("package");
  const returnTo = selectedPackage ? `/dashboard/membership?package=${encodeURIComponent(selectedPackage)}` : "/dashboard";
  return <main className="grid min-h-screen place-items-center bg-[#f7f8fc] px-4 py-10"><section className="w-full max-w-md rounded-3xl border border-slate-200 bg-white p-7 shadow-[0_22px_60px_rgba(16,35,63,.12)] sm:p-9"><button onClick={() => setLocation("/")} className="flex items-center gap-2 text-left font-extrabold text-[#10233f]"><span className="grid h-9 w-9 place-items-center rounded-xl bg-[#10233f] text-sm font-black text-[#6ee7dc]">F</span>FMB Earning Hub</button><div className="mt-10"><span className="grid h-12 w-12 place-items-center rounded-2xl bg-[#e9fbf8] text-[#13897f]"><ShieldCheck size={23} /></span><p className="mt-5 text-xs font-extrabold uppercase tracking-[.18em] text-[#13897f]">Member workspace</p><h1 className="mt-2 text-3xl font-extrabold tracking-[-.04em] text-[#10233f]">Member sign in</h1><p className="mt-3 text-sm leading-6 text-slate-600">{selectedPackage ? "After sign-in, your selected membership will be ready for payment verification." : "Use the member account provider to access packages, advertising activity, earnings, and withdrawal records."} Administrator access uses a separate local route.</p></div><Button onClick={() => startLogin(returnTo).catch((error: unknown) => { console.error("[Login] Google sign-in failed", error); alert(error instanceof Error ? error.message : "Sign-in failed. Please try again."); })} className="mt-7 h-11 w-full rounded-xl bg-[#10233f] font-bold hover:bg-[#19375f]"><LogIn className="mr-2" size={17} />Continue to member sign in</Button><Button onClick={() => setLocation("/admin-access")} variant="outline" className="mt-3 h-11 w-full rounded-xl border-slate-300 font-bold">Administrator access instead</Button><p className="mt-6 text-xs leading-5 text-slate-500">If external member verification is unavailable, use administrator access only if you are the designated administrator.</p></section></main>;
}
