import { Button } from "@/components/ui/button";
import { useAuth } from "@/_core/hooks/useAuth";
import { trpc } from "@/lib/trpc";
import { INITIAL_PACKAGES, formatDurationDays, formatPkr } from "@shared/platform";
import { ArrowLeft, ArrowRight, Check, ClipboardCheck, Contact, FileCheck2, HandCoins, Mail, MapPin, MessageCircle, Phone, type LucideIcon, ShieldCheck } from "lucide-react";
import { useLocation } from "wouter";

function PublicFrame({ children }: { children: React.ReactNode }) {
  const [, setLocation] = useLocation();
  return <div className="min-h-screen bg-[#f7f8fc] text-[#10233f]"><header className="border-b border-slate-200 bg-white"><div className="container flex h-[70px] items-center justify-between"><button onClick={() => setLocation("/")} className="flex items-center gap-2 font-extrabold"><span className="grid h-9 w-9 place-items-center rounded-xl bg-[#10233f] text-sm font-black text-[#6ee7dc]">F</span>FMB Earning Hub</button><div className="flex items-center gap-2"><Button variant="ghost" onClick={() => setLocation("/")} className="hidden font-bold sm:inline-flex"><ArrowLeft className="mr-2" size={16} />Home</Button><Button onClick={() => setLocation("/member-access")} className="rounded-xl bg-[#10233f] font-bold hover:bg-[#19375f]">Sign in</Button></div></div></header>{children}<footer className="mt-16 border-t border-slate-200 bg-white py-8"><div className="container text-xs leading-5 text-slate-500">Membership fees do not constitute an investment and the platform does not promise guaranteed profits or returns. Replace configuration placeholders and publish accurate policies before accepting payments.</div></footer></div>;
}

function PageHero({ eyebrow, title, description }: { eyebrow: string; title: string; description: string }) {
  return <section className="border-b border-slate-200 bg-white py-14 sm:py-18"><div className="container"><p className="text-xs font-extrabold uppercase tracking-[.19em] text-[#168d86]">{eyebrow}</p><h1 className="mt-3 max-w-3xl text-3xl font-extrabold tracking-[-.04em] sm:text-5xl">{title}</h1><p className="mt-5 max-w-2xl text-base leading-7 text-slate-600">{description}</p></div></section>;
}

export function PackagesPage() {
  const [, setLocation] = useLocation();
  const { isAuthenticated } = useAuth();
  const packages = trpc.platform.packages.useQuery();
  const list = packages.data?.length ? packages.data : INITIAL_PACKAGES;
  const selectPackage = (tier: typeof list[number]) => {
    const packageQuery = "id" in tier ? `?package=${tier.id}` : "";
    setLocation(`${isAuthenticated ? "/dashboard/membership" : "/member-access"}${packageQuery}`);
  };
  return <PublicFrame><PageHero eyebrow="Membership packages" title="Access terms with transparent advertising rules." description="Select a package only after reviewing its active terms. Package fees purchase membership access; they do not represent an investment or a promise of financial return." /><main className="container py-12"><div className="grid gap-5 lg:grid-cols-3">{list.map((tier, index) => <article key={tier.name} className={`rounded-[1.6rem] border p-6 ${index === 1 ? "border-[#e7cc70] bg-[#fffdf4]" : "border-slate-200 bg-white"}`}><p className="text-sm font-extrabold text-[#168d86]">{tier.name}</p><p className="mt-5 text-3xl font-extrabold">{formatPkr(tier.pricePaisa)}</p><p className="mt-1 text-sm text-slate-500">Membership fee</p><div className="mt-6 border-y border-slate-200 py-5"><div className="flex justify-between text-sm"><span className="text-slate-500">Eligible ad reward</span><strong>{formatPkr(tier.rewardPerEligibleAdPaisa)}</strong></div><div className="mt-3 flex justify-between text-sm"><span className="text-slate-500">Initial daily limit</span><strong>{tier.dailyAdLimit === 1 ? "1 campaign" : `${tier.dailyAdLimit} campaigns`}</strong></div><div className="mt-3 flex justify-between text-sm"><span className="text-slate-500">Initial duration</span><strong>{formatDurationDays(tier.durationDays)}</strong></div></div><ul className="mt-5 space-y-3">{(tier.features ?? []).map(feature => <li key={feature} className="flex gap-2 text-sm text-slate-600"><Check className="mt-0.5 text-[#16a097]" size={16} />{feature}</li>)}</ul><Button onClick={() => selectPackage(tier)} className="mt-7 w-full rounded-xl bg-[#10233f] font-bold hover:bg-[#19375f]">Select {tier.name}</Button></article>)}</div><div className="mt-8 rounded-2xl border border-[#bceee9] bg-[#f0fdfa] p-5 text-sm leading-6 text-[#176d68]"><strong>Before purchasing:</strong> Please review the package terms before completing payment. Membership fees are not investments; reward eligibility depends on available campaigns, completed verified activity, and current platform rules.</div></main></PublicFrame>;
}

export function HowItWorksPage() {
  const stages = [["Create an account", "Use your verified account to access the member workspace."], ["Select membership", "Review access rules and submit payment details for manual verification."], ["Receive approval", "An administrator verifies payment proof before access becomes active."], ["Complete eligible ads", "The server checks the active session, daily limits, and campaign budget."], ["Request withdrawal", "Eligible balance can be submitted for a documented review and payout process."]];
  return <PublicFrame><PageHero eyebrow="How it works" title="The platform follows a documented operational flow." description="This overview describes the intended process. It does not create an entitlement to advertising campaigns, rewards, or payment; all activity is subject to availability and published rules." /><main className="container py-12"><div className="mx-auto max-w-3xl space-y-4">{stages.map(([title, description], index) => <article key={title} className="flex gap-5 rounded-2xl border border-slate-200 bg-white p-5"><span className="grid h-10 w-10 shrink-0 place-items-center rounded-xl bg-[#e8fbf9] text-sm font-extrabold text-[#128b83]">{index + 1}</span><div><h2 className="font-extrabold">{title}</h2><p className="mt-2 text-sm leading-6 text-slate-600">{description}</p></div></article>)}</div></main></PublicFrame>;
}

const policyCopy: Record<string, { eyebrow: string; title: string; content: Array<[string, string]> }> = {
  about: { eyebrow: "About FMB Earning Hub", title: "A platform for validated advertising participation.", content: [["Purpose", "FMB Earning Hub is designed as an advertising rewards and digital membership platform. It is not an investment service, savings product, or return-generating scheme."], ["Operating principle", "The platform should fund reward activity only from legitimate available campaign budgets according to published terms and applicable requirements."], ["Transparency", "Company contact information, package settings, payment details, and published policies must be configured by an authorized administrator before the platform accepts live users."]] },
  terms: { eyebrow: "Terms & conditions", title: "Clear rules for access, activity, and account conduct.", content: [["Membership", "A membership provides access under its active rules after successful administrative payment verification. The platform may change package rules, availability, and terms with appropriate notice."], ["Eligible advertising rewards", "Rewards are contingent on available campaigns, verified completion, limits, and compliance checks. The platform makes no guarantee that campaigns will be available or that any particular amount will be earned."], ["Account controls", "Accounts may be placed under review or suspended when the platform identifies suspected abuse, security risk, duplicate activity, or breaches of applicable rules."], ["Withdrawals", "Withdrawal requests must satisfy the published minimum, fee, account-validation, and review rules. Processing status and payment references are documented in the member workspace."]] },
  privacy: { eyebrow: "Privacy policy", title: "Data used to operate securely and responsibly.", content: [["Information collected", "The platform may process account details, contact data, payment proof metadata, transaction records, device-security signals, and support communications."], ["Why it is collected", "Data is used to provide platform access, review payment proofs and withdrawals, prevent fraud, maintain transaction records, and meet legitimate operational or legal obligations."], ["Storage and access", "Sensitive payment information should be access-controlled and masked in routine user interfaces. Payment images must be validated before secure storage."], ["Your rights", "Publish the actual company’s applicable access, correction, deletion, complaint, and retention process before launch."]] },
  refunds: { eyebrow: "Refund policy", title: "A policy that must reflect the actual business process.", content: [["Before launch", "Replace this page with the company’s applicable refund terms, timeline, exclusions, contact route, and legal basis before accepting any membership payment."], ["Payment review", "Submitting a payment screenshot does not establish payment receipt or activate a package. An administrator records approval or rejection and may provide a documented reason."], ["Reversals", "If a withdrawal request is rejected or cancelled, the platform should process any balance release only under its published reversal rules and keep an audit entry."]] },
  disclosure: { eyebrow: "Risk & rewards disclosure", title: "No investment claims. No guaranteed returns.", content: [["Core disclosure", "Membership fees do not constitute an investment and the platform does not promise guaranteed profits or returns. Rewards are provided according to eligible advertising activity, available campaigns, package rules, and applicable platform terms."], ["What may change", "Campaign availability, reward amounts, daily limits, membership status, withdrawal requirements, fees, and operational policies may change in accordance with published platform rules."], ["What to avoid", "The platform must not communicate guaranteed income, unlimited earnings, doubled money, risk-free investment, or daily profit claims."]] },
};

export function PolicyPage({ kind }: { kind: keyof typeof policyCopy }) {
  const policy = policyCopy[kind];
  const settings = trpc.platform.settings.useQuery();
  const settingKey = kind === "terms" ? "terms_content" : kind === "privacy" ? "privacy_content" : kind === "refunds" ? "refund_content" : undefined;
  const configuredCopy = settingKey ? settings.data?.[settingKey] : undefined;
  const sections = configuredCopy ? [["Current configured policy", configuredCopy] as [string, string], ...policy.content] : policy.content;
  return <PublicFrame><PageHero eyebrow={policy.eyebrow} title={policy.title} description="This starter policy content is designed to be reviewed, localized, and replaced with the company’s accurate legal and operational information before public launch." /><main className="container py-12"><div className="mx-auto max-w-3xl space-y-5">{sections.map(([heading, copy]) => <article key={heading} className="rounded-2xl border border-slate-200 bg-white p-6"><h2 className="text-lg font-extrabold">{heading}</h2><p className="mt-3 text-sm leading-7 text-slate-600">{copy}</p></article>)}</div></main></PublicFrame>;
}

export function ContactPage() {
  const settings = trpc.platform.settings.useQuery();
  const data = settings.data;
  const items = [[Phone, "Phone", data?.contact_phone ?? "[YOUR SUPPORT PHONE]"], [MessageCircle, "WhatsApp", data?.whatsapp_number ?? "[YOUR WHATSAPP NUMBER]"], [Mail, "Email", data?.contact_email ?? "[YOUR SUPPORT EMAIL]"], [MapPin, "Address", data?.company_address ?? "[YOUR BUSINESS ADDRESS]"]];
  return <PublicFrame><PageHero eyebrow="Contact & support" title="Contact information that administrators can keep current." description="Use the support details below for platform questions. Replace all placeholders with the company’s verified contact information before public launch." /><main className="container py-12"><div className="grid gap-5 md:grid-cols-2">{(items as unknown as Array<[LucideIcon, string, string]>).map(([Icon, label, value]) => <article key={label} className="flex gap-4 rounded-2xl border border-slate-200 bg-white p-6"><span className="grid h-11 w-11 shrink-0 place-items-center rounded-xl bg-[#ebfbf9] text-[#13897f]"><Icon size={20} /></span><div><p className="text-xs font-bold uppercase tracking-[.14em] text-slate-500">{label}</p><p className="mt-2 text-sm font-extrabold text-[#10233f]">{value}</p></div></article>)}</div><section className="mt-5 rounded-2xl bg-[#10233f] p-6 text-white"><div className="flex gap-4"><Contact className="mt-1 text-[#6ee7dc]" /><div><p className="text-xs font-bold uppercase tracking-[.15em] text-[#7cebe1]">Support hours</p><p className="mt-2 text-lg font-extrabold">{data?.business_hours ?? "[YOUR BUSINESS HOURS]"}</p><p className="mt-3 max-w-2xl text-sm leading-6 text-slate-300">For account security, never post full payment information or credentials through informal support channels. Use the authenticated member workspace for payment proofs and withdrawal requests.</p></div></div></section></main></PublicFrame>;
}
